server:
  port: 3000 # puerto en el uqe escucha la aplicacion

spring: 
  datasource: 
    url: jdbc:postgresql://localhost:5332/customer
    username: user
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  main: 
   #  web-application-type: none # deshabilitar servidor web
   web-application-type: servlet #modo servlet (default)